source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
inhibit_all_warnings!

target 'TUIWeather' do
 pod 'SwiftLint','0.38.1'
 pod "PromiseKit", "~> 6.8"
end

target 'TUIWeatherTests' do
#    pod 'Quick', '2.2.0'
#    pod 'Nimble', '8.0.5'
end

post_install do |lib|
    lib.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end

